# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_Ingredients',
            fields=[
                ('dish_ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=10, verbose_name='Ingredient quantity')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Dish_Photos',
            fields=[
                ('dish_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo_source', models.CharField(max_length=200, verbose_name='Photo url')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_details', models.CharField(max_length=300, verbose_name='Dish details')),
                ('dish_rating', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.CharField(max_length=30, verbose_name='Ingredient name')),
                ('ingredient_type', models.CharField(max_length=30, verbose_name='Ingredient type')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Ingredients',
            fields=[
                ('recipe_ingredients_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=10, verbose_name='Ingredient quantity')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe_Method',
            fields=[
                ('recipe_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_text', models.CharField(max_length=500, verbose_name='Recipe method')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=200, verbose_name='Recipe name')),
                ('recipe_source', models.CharField(max_length=200, verbose_name='Recipe source')),
                ('recipe_type', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, verbose_name='Email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.AddField(
            model_name='recipes',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Users'),
        ),
        migrations.AddField(
            model_name='recipe_method',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Recipes'),
        ),
        migrations.AddField(
            model_name='recipe_ingredients',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Recipes'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Recipes'),
        ),
        migrations.AddField(
            model_name='dish_photos',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Dishes'),
        ),
        migrations.AddField(
            model_name='dish_ingredients',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Dishes'),
        ),
        migrations.AddField(
            model_name='dish_ingredients',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Ingredients'),
        ),
    ]
