# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dish_name',
            field=models.CharField(default='my_dish_name', max_length=200, verbose_name='Dish name'),
            preserve_default=False,
        ),
    ]
