# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0002_dishes_dish_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='dish_details',
            field=models.CharField(max_length=600, verbose_name='Dish details'),
        ),
    ]
