# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cooklog', '0003_auto_20161201_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('chef_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, verbose_name='Email address')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('dish_id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_name', models.CharField(max_length=200, verbose_name='Dish name')),
                ('dish_details', models.CharField(max_length=600, verbose_name='Dish details')),
                ('dish_rating', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=200, verbose_name='Recipe name')),
                ('recipe_source', models.CharField(max_length=200, verbose_name='Recipe source')),
                ('recipe_type', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(verbose_name='Date created')),
                ('chef_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Chef')),
            ],
        ),
        migrations.RenameModel(
            old_name='Dish_Photos',
            new_name='Dish_Photo',
        ),
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.RemoveField(
            model_name='dish_ingredients',
            name='dish_id',
        ),
        migrations.RemoveField(
            model_name='dish_ingredients',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='dishes',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='ingredient_id',
        ),
        migrations.RemoveField(
            model_name='recipe_ingredients',
            name='recipe_id',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='dish_photo',
            name='dish_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Dish'),
        ),
        migrations.AlterField(
            model_name='recipe_method',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Recipe'),
        ),
        migrations.DeleteModel(
            name='Dish_Ingredients',
        ),
        migrations.DeleteModel(
            name='Dishes',
        ),
        migrations.DeleteModel(
            name='Recipe_Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='dish',
            name='ingredient_id',
            field=models.ManyToManyField(to='cooklog.Ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cooklog.Recipe'),
        ),
    ]
